# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cypress Smoke Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "release" ]

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

jobs:
  test:

    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [20.11.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: echo ${{ env.MONGO_URI }}
      - run: echo ${{ secrets.MONGO_URI }}
      - run: yarn install
      - run: yarn build --if-present
      - run: yarn start &
      - run: yarn test
